title: Project Cobalt Blog
description: Updates and announcements from Project Cobalt
baseurl: "/secureinfra-blog"
url: "https://nmelo.github.io"
theme: minima

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
